meta_product_name: "icarebnb"
meta_title: "icarebnb - if you care"
meta_description: "Get involved to provide temporary accomodation for those most in need."
meta_image: "IcarebnbOG.png" # should exist in `app/assets/images/`

