meta_product_name: "icarebnb"
meta_title: "icarebnb - because you care"
meta_description: "If you care, icarebnb. We connect people who can volunteer a spare room with charities who are in contact with those most in need."
meta_image: "IcarebnbOG.png" # should exist in `app/assets/images/`

